export default [
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "module",
      globals: {
        wx: "readonly",
        Page: "readonly",
        App: "readonly",
        Component: "readonly",
        getApp: "readonly",
        getCurrentPages: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        Date: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        isNaN: "readonly",
        JSON: "readonly",
        Array: "readonly",
        Object: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        RegExp: "readonly",
        Error: "readonly",
        Math: "readonly"
      }
    },
    rules: {
      "no-unused-vars": "error",
      "no-undef": "error",
      "no-redeclare": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": "warn",
      "no-extra-semi": "error",
      "no-func-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-obj-calls": "error",
      "no-sparse-arrays": "error",
      "no-unexpected-multiline": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "curly": "warn",
      "eqeqeq": "warn",
      "no-eval": "warn",
      "no-implied-eval": "warn",
      "no-new-func": "warn",
      "no-script-url": "warn",
      "no-self-compare": "warn",
      "no-sequences": "warn",
      "no-throw-literal": "warn",
      "no-unmodified-loop-condition": "warn",
      "no-unused-expressions": "warn",
      "no-useless-call": "warn",
      "no-useless-concat": "warn",
      "radix": "warn",
      "wrap-iife": "warn",
      "yoda": "warn"
    }
  }
];
